# Basic python test script for travis-ci.org

language: python
python:
  - "3.4"
  - "3.5"
  - "2.7"
matrix:
  allow_failures:
    python: "3.4"
    python: "3.5"
install: pip install -r requirements-dev.txt
script:
  - nosetests
  - flake8
