# Basic python test script for travis-ci.org

language: python
dist: xenial
sudo: false
python:
  - "3.6"
  - "3.7"
  - "2.7"
install: pip install -r requirements-dev.txt
script:
  - nosetests
  - flake8
